var appConstants = {
    ADD_PLAYER: "ADD_PLAYER",
    REMOVE_PLAYER: "REMOVE_PLAYER",
    CHANGE_EVENT: "CHANGE_EVENT",
    MOVE_PLAYER: "MOVE_PLAYER",
    UPDATE_CURRENT_PLAYER: "UPDATE_CURRENT_PLAYER",
    NEW_PLAYER_EVENT: "NEW PLAYER_EVENT",
    NEW_PLAYER: "NEW_PLAYER",
    ADD_EVENT: "ADD_EVENT",
    REMOVE_EVENT: "REMOVE_EVENT"
};

module.exports = appConstants;
